on: [push]
name: build
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['9.6.2']
        cabal: ['3.0.0.0']
        os: [ubuntu-latest, macOS-latest, windows-latest]

    name: Haskell GHC ${{ matrix.ghc }} sample
    steps:
      - uses: actions/checkout@v3
      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Build binary
        run: |
          mkdir dist
          cabal install exe:pact-lsp --install-method=copy --overwrite-policy=always --installdir=dist
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: pact-lsp-${{matrix.os}}
          path: dist/
